title: Poem
subtitle: ポエムはじめました
repo: https://github.com/mzyy94/poem/raw/master/_posts/
author: mzyy94
twitter:
  username: mzyy94
disqus: mzyy94blog
color: limegreen
branch: master
remote_theme: mzyy94/jekyll-kieta-theme

permalink: /items/:title
search_engine: https://www.google.com/search
paginate: 5
paginate_path: "/page/:num"
jekyll-mentions: https://twitter.com
feed:
  path: /atom.xml

plugins:
  - jekyll-avatar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji

markdown: kramdown

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      true
  footnote_nr:    1
