title: Poem
subtitle: ポエムはじめました
repo: https://github.com/mzyy94/poem/blob/master/_posts/
author: mzyy94
github:
  username: mzyy94
twitter:
  username: mzyy94
disqus: mzyy94blog
color: limegreen

permalink: /items/:title
search_engine: https://www.google.com/search
paginate: 5 
paginate_path: "/page/:num"
jekyll-mentions: https://twitter.com
feed:
  path: /atom.xml

gems:
  - jekyll-avatar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      true
  footnote_nr:    1